name: Upload Python Package

on:
  release:
    types:
      - created
      - published
      - edited

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract package version from release tag
      run: echo "PACKAGE_VERSION=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Update version in setup.py
      run: |
        sed -i "s/{{VERSION_PLACEHOLDER}}/${{ env.PACKAGE_VERSION }}/g" setup.py

    - name: Build the package
      run: python -m build

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: twine upload dist/*
